### ISSUE TITLE
Installation: Could not find header files

### ISSUE THREAD

**Issue by jangirrishabh** [deepmind/dm_robotics#12]
Hi, the dm_robotics installed is unable to find the header files. Any help would be greatly appreciated!

ERROR:
'
In file included from /home/rishabh/workspace/dm_robotics/cpp/mujoco/src/mjlib.cc:15:
/home/rishabh/workspace/dm_robotics/cpp/mujoco/include/dm_robotics/mujoco/mjlib.h:22:10: fatal error: mjmodel.h: No such file or directory
   22 | #include "mjmodel.h"      //NOLINT
'

Here's my environment variables

'
MJLIB_PATH: /home/rishabh/.mujoco/mujoco/lib/libmujoco.so
Using cmake command 'cmake'
Using python command '/home/rishabh/anaconda3/envs/packing/bin/python'
Using tox command '/home/rishabh/anaconda3/envs/packing/bin/python -m tox'
Using python version '3.8'
'

**Comment by davidkh1** [comment]
Hi Rishabh,
Has the problem been solved? 
If you need help, could you share the Linux distribution you are using and what version of MuJoCo you have?

**Comment by jangirrishabh** [comment]
Thank you for getting back David!

Unfortunately not, here is my configuration. Somehow mjmodel.h inside .mujoco/mujoco/include/ is not being found

Linux: 22.04
Mujoco: Mujoco 2.0 (Installed from older mujoco not provided by deepmind)

If this is not the right config, how shall I proceed?

**Comment by jangirrishabh** [comment]
This was solved by installing mujoco from source.
