### ISSUE TITLE
dm_control 1.0.0 support

### ISSUE THREAD

**Issue by ikostrikov** [deepmind/dm_robotics#7]
Are you planning to add support for dm_control 1.0.0?

**Comment by shacklestone** [comment]
Yes, an update to version 1.0.2 will happen this week.

**Comment by ikostrikov** [comment]
Thank you so much!

**Comment by ikostrikov** [comment]
@shacklestone are there any updates? I wanted to use dm_robotics for a new project I'm working on, and it relies on some features introduced in the most recent versions of mujoco.

**Comment by BengineerZ** [comment]
Any update on this? Would love to bring up rgb-stacking to dm_control > 1.0.0 :)

**Comment by shacklestone** [comment]
Apologies for the delay, version 0.4.0 has been released it uses dm_control 1.0.1 and mujoco 2.1.3
It is not compatible with mujoco >= 2.2.0
